version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: syscall
              desc: Use golang.org/x/sys instead
    funlen:
      lines: 100
      statements: 60
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G107
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - gocyclo
          - paralleltest
        path: _test.go$
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: don't use underscores in Go names
    paths:
      - vendor
      - gen
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default: warning
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - gen
      - third_party$
      - builtin$
      - examples$
